# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: selfdev
service: AWSLambdawithGHAction
provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-north-1

functions:
  hello:
    handler: src/handler:generateRandomNumber